### PR TITLE
INFRA-3543: delete in batches of 100

### PR DESCRIPTION
**Pull request by aastein**
Delete images in batches of 100, the maximum amount for BatchDeleteImage.
https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_BatchDeleteImage.html

tested with: https://play.golang.org/p/lKp2cF042HD

### CODE REVIEW

**Comment by aastein** [comment]
A few apps have repos with > 200 images, does this info seem right / is expected?

apps-dashboard:702
catapult:296
district-store:270
hall-monitor:325
launchpad:326
oauth:357
redshift-respawn:250
redshift-to-postgres:244
reports-dashboard:608
reports-worker:375
roster-search-service:201
sd2:215
storefront:203
workflow-manager:313

**Comment by rgarcia** [comment]
hm... hard to know since we push images on non-master branches. Maybe spot check a few of these and make sure we're not deleting recent master builds?

**Comment by aastein** [comment]
How can I know what branch these images are for?

I checked a few in AWS console. Things look good as far as deleting the images we expect to be deleted with the current logic. Seems like us-west-1 repos were never pruned? A lot of builds starting on 2017.

**Comment by rgarcia** [comment]
huh, us-west-1 repos should have been pruning for a while. Maybe the worker was broken before... The way I would spot check would be to look at `ark builds <app>` and make sure we're not nuking recent builds by comparing it to the image tags

**Comment by aastein** [comment]
Checked the builds, things look good. I see how it was broken before... 🕵️‍♂️

Delete images did not return an error
https://github.com/Clever/prune-images/blob/c39a8ce939ea9a31113621d0e47376cfd3f5a98e/handler.go#L62

and the delete API call didn't properly log errors
https://github.com/Clever/prune-images/blob/c39a8ce939ea9a31113621d0e47376cfd3f5a98e/lib/ecr/ecr.go#L69-L74

and a limit was never set on the amount of images the batchDelete API was sent. So if a repo had more than 200 images when the worker ran, the repo would silently fail to get pruned.

**Pull request merged**
